package com.java.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-03-29T20:29:00.686-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://provider.java.com/", name = "EmployeeProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeProvider {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "remove", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.RemoveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean remove(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "list", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.ListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.java.proxy.Employee> list();

    @WebMethod
    @RequestWrapper(localName = "findEmployee", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.FindEmployee")
    @ResponseWrapper(localName = "findEmployeeResponse", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.FindEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean findEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findByName", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.FindByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.java.proxy.Employee> findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://provider.java.com/", className = "com.java.proxy.UpdateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
